version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: camunda-postgres
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
      POSTGRES_DB: camunda
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zeebe:
    image: camunda/zeebe:8.5.4
    container_name: zeebe
    environment:
      ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME: io.camunda.zeebe.exporter.debug.DebugExporter
      ZEEBE_BROKER_DATA_PARTITIONSCOUNT: "1"
      ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT: "1"
    ports:
      - "26500:26500"

  operate:
    image: camunda/operate:8.5.4
    container_name: camunda-operate
    environment:
      CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS: zeebe:26500
    ports:
      - "8081:8080"

  tasklist:
    image: camunda/tasklist:8.5.4
    container_name: camunda-tasklist
    environment:
      CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS: zeebe:26500
    ports:
      - "8082:8080"

  optimize:
    image: camunda/optimize:8.5.4
    container_name: camunda-optimize
    environment:
      OPTIMIZE_ZEEBE_GATEWAY: zeebe:26500
    ports:
      - "8083:8080"

volumes:
  pgdata:
