spring:
  application:
    name: talent-screening

  datasource:
    url: jdbc:postgresql://localhost:5432/trackerdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect